version: "3.8"
services:
  argenpesos-frontend:
    container_name: argenpesos-frontend
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - argenpesos_network

networks:
  argenpesos_network:
